name: Payout Managers

on:
  schedule:
    - cron: "15 0 * * SUN" # Every Sunday at 00:15 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - run: npm ci
      - name: Payout the Lottery Managers
        run: npm run payout
        env:
          EXECUTOR_MNEMONIC: ${{ secrets.EXECUTOR_MNEMONIC }}
          NETWORK: ${{ secrets.NETWORK }}
